# Generated by Django 5.2.12 on 2026-04-10 20:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_blogpostpage_relations_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("section_heading", 2),
                    ("rich_text", 3),
                    ("callout", 7),
                    ("code", 11),
                    ("mermaid", 12),
                    ("plantuml", 17),
                    ("figure", 16),
                ],
                blank=True,
                use_json_field=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 60, "required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 120, "required": True}),
                    2: ("wagtail.blocks.StructBlock", [[("eyebrow", 0), ("title", 1)]], {}),
                    3: (
                        "cms.blocks.RichSectionBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "h2",
                                "h3",
                                "blockquote",
                                "code",
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 120, "required": False}),
                    5: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success"), ("warning", "Warning"), ("danger", "Danger")]},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("title", 4), ("text", 5), ("tone", 6)]], {}),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("django", "Django / HTML+Django"),
                                ("csharp", "C#"),
                                ("javascript", "JavaScript"),
                                ("typescript", "TypeScript"),
                                ("json", "JSON"),
                                ("yaml", "YAML"),
                                ("bash", "Bash"),
                                ("sql", "SQL"),
                                ("docker", "Dockerfile"),
                                ("xml", "XML"),
                                ("text", "Plain text"),
                            ]
                        },
                    ),
                    9: ("wagtail.blocks.BooleanBlock", (), {"default": True, "required": False}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("narrow", "Narrow"),
                                ("content", "Content width"),
                                ("wide", "Wide"),
                                ("full", "Full width"),
                            ]
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("caption", 4), ("language", 8), ("code", 5), ("show_line_numbers", 9), ("width", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("caption", 4), ("diagram", 5), ("width", 10)]], {}),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    14: ("wagtail.blocks.CharBlock", (), {"max_length": 180, "required": False}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 13), ("caption", 14), ("alt_text", 14), ("alignment", 15), ("width", 10)]],
                        {},
                    ),
                    17: ("wagtail.blocks.StructBlock", [[("caption", 4), ("source", 5), ("width", 10)]], {}),
                },
            ),
        ),
    ]
