# Generated by Django 5.2.12 on 2026-04-10 22:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_plantuml_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('section_heading', 2), ('rich_text', 3), ('callout', 7), ('code', 11), ('mermaid', 12), ('plantuml', 14), ('figure', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1)]], {}), 3: ('cms.blocks.RichSectionBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3', 'blockquote', 'code']}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')]}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5), ('tone', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('django', 'Django / HTML+Django'), ('csharp', 'C#'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('json', 'JSON'), ('yaml', 'YAML'), ('bash', 'Bash'), ('sql', 'SQL'), ('docker', 'Dockerfile'), ('xml', 'XML'), ('text', 'Plain text')]}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('narrow', 'Narrow'), ('content', 'Content width'), ('wide', 'Wide'), ('full', 'Full width')]}), 11: ('wagtail.blocks.StructBlock', [[('caption', 4), ('language', 8), ('code', 5), ('show_line_numbers', 9), ('width', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('caption', 4), ('diagram', 5), ('width', 10)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste PlantUML source. You may include or omit @startuml / @enduml.', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('caption', 4), ('source', 13), ('width', 10)]], {}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 18: ('wagtail.blocks.StructBlock', [[('image', 15), ('caption', 16), ('alt_text', 16), ('alignment', 17), ('width', 10)]], {})}),
        ),
    ]
