apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: ai-blog-local
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-me-for-local-k8s-demo"
  DJANGO_DB_NAME: "ai_powered_blog"
  DJANGO_DB_USER: "postgres"
  DJANGO_DB_PASSWORD: "postgres"
