apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ai-blog-local
type: Opaque
stringData:
  POSTGRES_DB: ai_powered_blog
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
